/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Moonwise (https://sketchfab.com/Moonwise)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/night-sky-aebbd4f5b37a4dfd8e3556de9084bae9
Title: Night sky
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

import baloon from "../assets/3d/night_sky.glb";

export default function Model({ isRotating, ...props }) {
  const baloonRef = useRef();
  const { nodes, materials } = useGLTF(baloon);

  return (
    <group
      {...props}
      ref={baloonRef}
      position={props.baloonPosition}
      scale={props.baloonScale}
    >
      <group position={[0, -11.051, -4.906]} scale={[7.683, 5.769, 7.683]}>
        <mesh geometry={nodes.Object_6.geometry} material={materials.White} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.Black} />
      </group>
      <group
        position={[-9.653, -9.826, -4.77]}
        rotation={[0, 0, -0.373]}
        scale={1.911}
      >
        <mesh geometry={nodes.Object_9.geometry} material={materials.White} />
        <mesh geometry={nodes.Object_10.geometry} material={materials.Black} />
      </group>
      <group
        position={[0, 16.232, -4.906]}
        rotation={[0, 1.343, 0]}
        scale={[16.315, 17.967, 16.315]}
      >
        <mesh geometry={nodes.Object_12.geometry} material={materials.Black} />
        <mesh geometry={nodes.Object_13.geometry} material={materials.White} />
      </group>
    </group>
  );
}

useGLTF.preload("/night_sky.glb");
