/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Moonwise (https://sketchfab.com/Moonwise)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/night-sky-aebbd4f5b37a4dfd8e3556de9084bae9
Title: Night sky
*/

import React, { useEffect, useRef } from "react";
import { useAnimations, useGLTF } from "@react-three/drei";

import bat from "../assets/3d/vampire_glow_bat.glb";
import { useFrame } from "@react-three/fiber";

export default function Model(props) {
  const batRef = useRef();
  const { nodes, materials, scene, animations } = useGLTF(bat);
  const { actions } = useAnimations(animations, batRef);

  useEffect(() => {
    actions["Fly"].play();
  }, []);

  useFrame(({ clock, camera }) => {
    batRef.current.position.y = Math.sin(clock.getElapsedTime()) * 0.2 + 2;

    if (batRef.current.position.x > camera.position.x + 10) {
      batRef.current.rotation.y = Math.PI;
    } else if (batRef.current.position.x < camera.position.x - 10) {
      batRef.current.rotation.y = 0;
    }

    if (batRef.current.rotation.y === 0) {
      batRef.current.position.x += 0.007;
      batRef.current.position.z -= 0.007;
    } else {
      batRef.current.position.x -= 0.007;
      batRef.current.position.z += 0.007;
    }
  });

  return (
    <group
      ref={batRef}
      {...props}
      position={[-10, 0, -4]}
      scale={[0.02, 0.02, 0.02]}
      rotation={[0, 0, 0]}
    >
      <group name="Sketchfab_Scene" rotation={[0, 2, 0]}>
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="Sketchfab_model_0" rotation={[-Math.PI / 2, 0, 0]}>
                <group
                  name="c60bc758ef564487a3b896e7cb3dc0cafbx_1"
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={0.01}
                >
                  <group name="Object_2_2">
                    <group name="RootNode_3">
                      <group name="Object_4_4">
                        <group name="GLTF_created_0">
                          <primitive object={nodes.GLTF_created_0_rootJoint} />
                          <skinnedMesh
                            name="Object_48"
                            geometry={nodes.Object_48.geometry}
                            material={materials.material}
                            skeleton={nodes.Object_48.skeleton}
                          />
                          <group name="Object_7_7_correction">
                            <group name="Object_7_7" />
                          </group>
                        </group>
                      </group>
                    </group>
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}
