/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: rudolfs (https://sketchfab.com/rudolfs)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/felix-the-cat-6c6fa5c8512a4659a37469f869199b1b
Title: Felix The Cat
*/

import React, { useRef, useEffect } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame, useThree } from "@react-three/fiber";
import { a } from "@react-spring/three";

import felixScene from "../assets/3d/felix_the_cat.glb";

export default function Model({
  isRotating,
  setIsRotating,
  setCurrentStage,
  ...props
}) {
  const felixRef = useRef();

  const { gl, viewport } = useThree();
  const { nodes, materials } = useGLTF(felixScene);

  const lastX = useRef(0);
  const rotationSpeed = useRef(0);
  const dampingFactor = 0.95;

  // Swipe handling variables
  const swipeStart = useRef({ x: 0, y: 0 });
  const swipeEnd = useRef({ x: 0, y: 0 });
  const swipeThreshold = 50; // Minimum swipe distance to consider it a valid swipe

  // Pointer Event Handlers
  const handlePointerDown = (e) => {
    e.stopPropagation();
    e.preventDefault();
    setIsRotating(true);

    const clientX = e.touches ? e.touches[0].clientX : e.clientX;

    lastX.current = clientX;
  };

  const handlePointerUp = (e) => {
    e.stopPropagation();
    e.preventDefault();
    setIsRotating(false);
  };

  const handlePointerMove = (e) => {
    e.stopPropagation();
    e.preventDefault();

    if (isRotating) {
      const clientX = e.touches ? e.touches[0].clientX : e.clientX;

      const delta = (clientX - lastX.current) / viewport.width;

      felixRef.current.rotation.y += delta * 0.01 * Math.PI;
      lastX.current = clientX;
      rotationSpeed.current = delta * 0.01 * Math.PI;
    }
  };

  // Keyboard Event Handlers
  const handleKeyDown = (e) => {
    if (e.key === "ArrowLeft") {
      if (!isRotating) setIsRotating(true);
      felixRef.current.rotation.y += 0.01 * Math.PI;
      rotationSpeed.current = 0.0125;
    } else if (e.key === "ArrowRight") {
      if (!isRotating) setIsRotating(true);
      felixRef.current.rotation.y -= 0.01 * Math.PI;
      rotationSpeed.current = -0.0125;
    }
  };

  const handleKeyUp = (e) => {
    if (e.key === "ArrowLeft" || e.key === "ArrowRight") {
      setIsRotating(false);
    }
  };

  // Swipe Event Handlers
  const handleTouchStart = (e) => {
    const touch = e.touches[0];
    swipeStart.current = { x: touch.clientX, y: touch.clientY };
  };

  const handleTouchMove = (e) => {
    const touch = e.touches[0];
    swipeEnd.current = { x: touch.clientX, y: touch.clientY };
  };

  const handleTouchEnd = () => {
    const deltaX = swipeEnd.current.x - swipeStart.current.x;
    const deltaY = swipeEnd.current.y - swipeStart.current.y;

    if (
      Math.abs(deltaX) > Math.abs(deltaY) &&
      Math.abs(deltaX) > swipeThreshold
    ) {
      if (deltaX > 0) {
        // Swipe Right
        felixRef.current.rotation.y -= 0.05 * Math.PI;
        setCurrentStage((prev) => (prev - 1 >= 1 ? prev - 1 : 4)); // Adjust stage
      } else {
        // Swipe Left
        felixRef.current.rotation.y += 0.05 * Math.PI;
        setCurrentStage((prev) => (prev + 1 <= 4 ? prev + 1 : 1)); // Adjust stage
      }
    }

    // Reset swipe positions
    swipeStart.current = { x: 0, y: 0 };
    swipeEnd.current = { x: 0, y: 0 };
  };

  useFrame(() => {
    if (!isRotating) {
      rotationSpeed.current *= dampingFactor;

      if (Math.abs(rotationSpeed.current) < 0.001) {
        rotationSpeed.current = 0;
      }

      felixRef.current.rotation.y += rotationSpeed.current;
    } else {
      const rotation = felixRef.current.rotation.y;

      const normalizedRotation =
        ((rotation % (2 * Math.PI)) + 2 * Math.PI) % (2 * Math.PI);

      console.log(normalizedRotation);
      // Set the current stage based on the island's orientation
      switch (true) {
        case normalizedRotation >= 0.85 && normalizedRotation <= 1.5:
          setCurrentStage(1);
          break;
        case normalizedRotation >= 5.45 && normalizedRotation <= 5.85:
          setCurrentStage(2);
          break;
        case normalizedRotation >= 3.5 && normalizedRotation <= 4:
          setCurrentStage(3);
          break;
        case normalizedRotation >= 2 && normalizedRotation <= 2.5:
          setCurrentStage(4);
          break;
        default:
          setCurrentStage(null);
      }
    }
  });

  useEffect(() => {
    const canvas = gl.domElement;

    // Pointer Events
    canvas.addEventListener("pointerdown", handlePointerDown);
    canvas.addEventListener("pointerup", handlePointerUp);
    canvas.addEventListener("pointermove", handlePointerMove);

    // Keyboard Events
    document.addEventListener("keydown", handleKeyDown);
    document.addEventListener("keyup", handleKeyUp);

    // Touch Events for Swipe Handling
    canvas.addEventListener("touchstart", handleTouchStart);
    canvas.addEventListener("touchmove", handleTouchMove);
    canvas.addEventListener("touchend", handleTouchEnd);

    return () => {
      // Clean up Pointer Events
      canvas.removeEventListener("pointerdown", handlePointerDown);
      canvas.removeEventListener("pointerup", handlePointerUp);
      canvas.removeEventListener("pointermove", handlePointerMove);

      // Clean up Keyboard Events
      document.removeEventListener("keydown", handleKeyDown);
      document.removeEventListener("keyup", handleKeyUp);

      // Clean up Touch Events
      canvas.removeEventListener("touchstart", handleTouchStart);
      canvas.removeEventListener("touchmove", handleTouchMove);
      canvas.removeEventListener("touchend", handleTouchEnd);
    };
  }, [gl, isRotating]);

  return (
    <a.group {...props} ref={felixRef}>
      <group
        position={[0.661, -15, -4.092]}
        rotation={[-Math.PI / 2, 0.2, 0.5]}
      >
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group
            position={[75.653, -2.203, 385.15]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={92.089}
          >
            <mesh
              geometry={nodes.Cube007_Material_0.geometry}
              material={materials.Material}
            />
            <mesh
              geometry={nodes.Cube007_Material001_0.geometry}
              material={materials["Material.001"]}
            />
          </group>
          {/* FENCE */}
          {/* <group
            position={[438.132, 126.904, 427.671]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={86.918}
          >
            <mesh
              geometry={nodes.Cube006_Material_0.geometry}
              material={materials.Material}
            />
            <mesh
              geometry={nodes.Cube006_Material001_0.geometry}
              material={materials["Material.001"]}
            />
          </group> */}

          <group
            position={[265.493, 91.524, 47.2]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={92.089}
          >
            <mesh
              geometry={nodes.Cylinder002_Material_0.geometry}
              material={materials.Material}
            />
            <mesh
              geometry={nodes.Cylinder002_Material001_0.geometry}
              material={materials["Material.001"]}
            />
          </group>
          <group
            position={[47.75, -2.203, 47.2]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={92.089}
          >
            <mesh
              geometry={nodes.Cylinder001_Material001_0.geometry}
              material={materials["Material.001"]}
            />
            <mesh
              geometry={nodes.Cylinder001_Material002_0.geometry}
              material={materials["Material.002"]}
            />
          </group>
          <group scale={100}>
            <mesh
              geometry={nodes.Group2064002_Material001_0.geometry}
              material={materials["Material.001"]}
            />
            <mesh
              geometry={nodes.Group2064002_Material_0.geometry}
              material={materials.Material}
            />
          </group>
          <group scale={100}>
            <mesh
              geometry={nodes.Group2064_Material_0.geometry}
              material={materials.Material}
            />
            <mesh
              geometry={nodes.Group2064_Material001_0.geometry}
              material={materials["Material.001"]}
            />
          </group>
          <mesh
            geometry={nodes.Plane002_Material_0.geometry}
            material={materials.Material}
            position={[0.311, 223.604, 161.744]}
            rotation={[1.293, -0.014, 0]}
            scale={11.386}
          />
          <mesh
            geometry={nodes.Sphere001_Material001_0.geometry}
            material={materials["Material.001"]}
            position={[47.009, 889.502, 46.787]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={19.726}
          />
          <mesh
            geometry={nodes.Cylinder_Material002_0.geometry}
            material={materials["Material.002"]}
            position={[47.75, -2.203, 47.2]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={92.089}
          />
        </group>
      </group>
    </a.group>
  );
}
